<?php

namespace AppBundle\Repository;

/**
 * AvtoOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvtoOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
