<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CartridgeOrder;

/**
 * CartridgeOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartridgeOrderRepository extends \Doctrine\ORM\EntityRepository
{

}
