<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CartridgeOrder;

/**
 * CartridgeOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartridgeOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateUserStatus($login, $password, $id)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();
        $query->update('AppBundle:CartridgeOrder', 'co')
            ->set('co.status', '?1')
            ->set('co.issued', '?2')
            ->where('co.id = ?3')
            ->setParameter(1, $login)
            ->setParameter(2, $password)
            ->setParameter(3, $id)
            ->getQuery()
            ->execute();
    }

    public function getCount()
    {
        $results = $this
            ->createQueryBuilder('cartridge_order')
            ->getQuery()
            ->getResult()
        ;
        $resultCount = count($results);
        return $resultCount;
    }

}
