<?php

namespace AppBundle\Repository;

/**
 * CartridgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartridgeRepository extends \Doctrine\ORM\EntityRepository
{
}
