<?php

namespace AppBundle\Repository;

/**
 * CartridgeOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartridgeOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
