<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cartridge;

/**
 * CartridgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartridgeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Cartridge[]
     */
    public function findExistCartridge()
    {
        return $this
            ->createQueryBuilder('cartridge')
            ->where('cartridge.exist = 1')
            ->getQuery()
            ->getResult()
        ;

    }

    public function countCartridge()
    {
        $results = $this
            ->createQueryBuilder('cartridge')
            ->where('cartridge.exist = 1')
            ->getQuery()
            ->getResult()
            ;
        $resultCount = count($results);
        return $resultCount;

    }
}
