<?php

namespace AppBundle\Repository;

/**
 * ConsultationOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function countOrder()
    {
        $results = $this
            ->createQueryBuilder('consultation')
            ->getQuery()
            ->getResult()
        ;
        $resultCount = count($results);
        return $resultCount;
    }
}
