<?php

namespace AppBundle\Repository;

/**
 * HandBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandBookRepository extends \Doctrine\ORM\EntityRepository
{
}
