<?php

namespace AppBundle\Repository;

/**
 * ImproveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImproveRepository extends \Doctrine\ORM\EntityRepository
{
}
