<?php

namespace AppBundle\Repository;

/**
 * MailPassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailPassRepository extends \Doctrine\ORM\EntityRepository
{
}
