<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cartridge;

/**
 * PrinterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrinterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCartridgeId(Cartridge $cartridge)
    {
        return $this
            ->createQueryBuilder('printer')
            ->where('printer.cartridgeModel = :cartridgeModel')
            ->setParameter('cartridgeModel', $cartridge)
            ->getQuery()
            ->getResult()
            ;
    }
}
