<?php

namespace AppBundle\Repository;

/**
 * PrinterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrinterRepository extends \Doctrine\ORM\EntityRepository
{
}
