<?php

namespace AppBundle\Repository;

/**
 * SrvPassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SrvPassRepository extends \Doctrine\ORM\EntityRepository
{
}
