<?php

namespace AppBundle\Repository;

/**
 * WebAccountsPassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebAccountsPassRepository extends \Doctrine\ORM\EntityRepository
{
}
