<?php

namespace AppBundle\Repository;

/**
 * WebInterfacePassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebInterfacePassRepository extends \Doctrine\ORM\EntityRepository
{
}
