<?php

namespace AppBundle\Repository;

/**
 * WebInterfaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebInterfaceRepository extends \Doctrine\ORM\EntityRepository
{
}
