<?php

namespace AppBundle\Repository;

/**
 * ЦС�CabinetPassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ЦС�CabinetPassRepository extends \Doctrine\ORM\EntityRepository
{
}
